### PR TITLE
Fixes issue #1501 - Add support for multi-releases Jar

### LINKED ISSUE #1501: Add support for multi-releases Jar
Weld is going to release a fix to https://github.com/piranhacloud/piranha/issues/1428. However, as it wants to be compatible with JDK 8+, they will be using multi-releases Jar [1]

The JarFile class already supports it, so Piranha Server should be OK, but the other in-memory resources are not. 

[1] https://issues.redhat.com/browse/WELD-2581

### PR DESCRIPTION
**Pull request by Thihup**
This is a very naive implementation of the multi-release resource wrapper that probably needs some performance improvement. However, it is enough to load the Weld multi-release jar.

It still needs to change the Piranha Micro to use this wrapper

Fixes #1501

### CODE REVIEW

File: resource/impl/src/main/java/cloud/piranha/resource/MultiReleaseResource.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+            return resource.getResource(location);
+        }
+        return versionedResource(location);
+    }
+
+    private URL versionedResource(String location) {
+        if (location.startsWith(META_INF))
+            return resource.getResource(location);
+
+        // Java 9 added support for multi-release jars
```
Comment (manorrock) [inline resource/impl/src/main/java/cloud/piranha/resource/MultiReleaseResource.java:108]: Can you put this in a JavaDoc comment for this method?

File: resource/impl/src/main/java/cloud/piranha/resource/MultiReleaseResource.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+import java.net.URL;
+import java.util.Objects;
+import java.util.jar.Attributes;
+import java.util.jar.Manifest;
+import java.util.stream.IntStream;
+import java.util.stream.Stream;
+
+/**
+ * A resource wrapper that loads the classes from META-INF/versions if
+ * the resource contains the Multi-Release: true in the MANIFEST.MF
```
Comment (manorrock) [inline resource/impl/src/main/java/cloud/piranha/resource/MultiReleaseResource.java:45]: Can you elaborate a bit more about how it works here? E.g how the versions are resolved?

**Comment by Thihup** [comment]
The implementation is not very performant because it tries each version from the current release until version 9, probably implementing a fast-path for versions 9 and 11 should help when there is a multi-release entry (these are the most used entries so far).

Maybe would be possible to cache all the multi-release entries, but this should have an increased memory consumption, so I'm having a hard time choosing the best way to improve the performance. I'm thinking of opening an issue to handle it later.
