### PR TITLE
Fixes issue #1228 - Start Piranha Server using JPMS by default

### LINKED ISSUE #1228: Start Piranha Server using JPMS by default
#1104

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1228 

It was needed to set the java.ext.dirs property because the Jasper cannot find the classes by setting the classpath to jdk.module.path. 
However, the jdk.module.path property contains only "lib" and the Jasper only understands all jars specified (no wildcard or directories).
By settings the java.ext.dirs property, we can supply the folder directly to javac compiler.

### CODE REVIEW

File: pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperInitializer.java [hunk 1]
```diff
@@ -132,4 +132,10 @@ public void onStartup(Set<Class<?>> classes, ServletContext servletContext) thro
 
         LOGGER.fine("Initialized Jasper integration");
     }
+
+    static {
+        // This is a hack until Jasper handles JPMS
+        if (JasperInitializer.class.getModule().isNamed())
+            System.setProperty("java.ext.dirs", System.getProperty("jdk.module.path"));
```
Comment (manorrock) [inline pages/jasper/src/main/java/cloud/piranha/pages/jasper/JasperInitializer.java:139]: Can you check if it is already set and then take that into account?
